version: "3.8"
services:
  lgp-app:
    env_file:
      - path: ../.env
    environment:
      - AIR_API_KEY:${AIR_API_KEY}
    build:
      context: ..
      dockerfile: ci/Dockerfile
    container_name: iss-setter
    volumes:
      - .:/iss-setter
    ports:
      - "8050:8050"  # Adjust if your app uses a different port

