name: cd-test for noti

on:
  push:
    branches:
      - noti-1727-test

jobs:
  call-workflow-using-pat:
    uses: ./.github/workflows/create-and-post-tag.yml
    secrets: inherit

  # pre-tag-summary:
    # needs: deploy-to-perf
    # uses: ./.github/workflows/pre-tag-summary.yml
    # secrets: inherit

  merge-to-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: release
          fetch-depth: 0
          # Fine-grained PAT with contents:write and workflows:write
          # scopes
          # token: ${{ secrets.CD_PAT_VAR }}

      - name: Setup git user
        # The following is taken from https://github.com/actions/checkout/issues/13 as a common work-around
        run: |
            git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
            git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          
      - name: Merge commit SHA to release
        run: |
          git merge ${{ github.sha }} --no-squash -X theirs
          git push

  # create-and-post-tag:
    # needs: merge-to-release
    # uses: ./.github/workflows/create-and-post-tag.yml
    # secrets: inherit

  # deploy-to-staging:
    # needs: merge-to-release 
    # uses: ./.github/workflows/dev_deploy.yml
    # with:
      # environment: staging
      # ref: release
      # lambdaDeploy: true
    # secrets: inherit

  # QA-approval-of-staging:
    # needs: deploy-to-staging
    # environment: 
      # name: prod-deploy
    # runs-on: ubuntu-latest
    # steps:
      # - name: Pause for manual approval
        # run: echo "Pipeline paused for pending approval of staging by QA"

