name: Create Release Notes

on: 
  workflow_call:
    inputs:
      previousVersion:
        required: true
        type: string
    outputs:
      draftReleaseReference:
        description: "This value is the id that will be used when actually publishing this release notes"
        value: ${{ jobs.create-release-notes.outputs.draftReleaseReference }}

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    outputs:
      draftReleaseReference: ${{ steps.create_notes.outputs.draftReleaseReference }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: List .github directory contents
        run: ls -R .github

      - name: Create Release Notes
        id: create_notes
        uses: actions/github-script@v7
        env:
          previousVersion: ${{ inputs.previousVersion }}
        with:
          github-token: ${{ secrets.VAR_PAT }}
          # This script outputs draftReleaseReference for publish-release-notes.yml
          script: |
            const createReleaseNotes = require('.github/scripts/createReleaseNotes.js');
            const fs = require('fs');
            const path = require('path');

            // Log current working directory
            console.log('Current directory:', process.cwd());

            // Log .github directory contents
            console.log('Files in .github directory:', fs.readdirSync(path.join(process.cwd(), '.github')));

            createReleaseNotes({github, context, core});

