name: Delete Tags

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      tag(s):
        description: 'the tag(s) you want to delete'

jobs:
  delete-tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Delete Tags
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TAG_PAT }}
          script: |
            const deleteTags = require('.github/scripts/deleteTags.js');
            deleteTags({github, context, core});

