name: Delete Tag(s)

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      ref(s):
        description: 'the tag(s) you want to delete'

jobs:
  create-and-post-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # - name: Create and Post Tag
        # id: create_tag
        # uses: actions/github-script@v7
        # with:
          # github-token: ${{ secrets.VAR_PAT }}
          # # This script outputs previousVersion for create-release-notes.yml
          # script: |
            # const createAndPostTag = require('.github/scripts/createAndPostTag.js');
            # createAndPostTag({github, context, core});

