name: Delete Non-V Tags

on:
  workflow_dispatch:

jobs:
  delete-non-v-tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Delete Non-V Tags
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TAG_PAT }}
          script: |
            const deleteNonVTags = require('./.github/scripts/deleteNonVTags.js');
            deleteNonVTags({github, context, core});

