name: api deploy

on:
  workflow_call:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: "dev"
        type: string
      ref:
        description: 'Git reference to deploy'
        required: true
        default: "master"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  wait-for-approval:
    runs-on: ubuntu-latest
    needs: build
    # if: github.ref == 'refs/heads/main' # Ensure this job runs only for the main branch
    environment:
      name: perf
    steps:
      - name: Pause for manual approval
        run: echo "Waiting for manual approval..."

  deploy:
    needs: wait-for-approval
    runs-on: ubuntu-latest
    steps:
      - name: Deployment step
        run: echo "Deploying to performance environment..."

