# .github/workflows/deploy-release.yml
# This workflow should only be run when a release or prerelease need to be deployed outside the cd-pipeline.yml
# dev_deploy.yml only deploys hashes - this workflow ensures the tag is deployed
# this ensures the tag name shows up correctly in Datadog for deployment tracking
name: Deploy API Release
run-name: "Deploy Release to ${{ inputs.environment }}"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to deploy
        default: dev
        options:
          - dev
          - perf
          - staging
          - prod
      ref:
        description: "Tag, branch, or commit"
        default: master
        required: true
        type: string
      lambdaDeploy:
        description: "Include Lambda in deployment?"
        default: true
        required: false
        type: boolean
  workflow_call:
    inputs:
      environment:
        type: string
        default: dev
      ref:
        default: "dev"
        description: "Tag, branch, or commit"
        required: true
        type: string
      lambdaDeploy:
        description: "Include Lambda in deployment?"
        default: true
        required: false
        type: boolean

env:
  TAG: ${{ inputs.ref }}
  ENV: ${{ inputs.environment }}

jobs:
  test-tag-value:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.TAG }}

      - name: Test tag deploy value
        run: |
          echo "checked out tag: ${{ env.TAG }}"
          echo "the environment is ${{ env.ENV }}"

